import ProjectDescription

let workspace = Workspace(
  name: "Prowl",
  projects: [
    ".",
    "MirrorClient/iOS",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled
  )
)
