// supacode/CLIService/HandoffCommandHandler.swift

import Foundation

/// A handoff source resolved on the main actor: the runnable root to store the
/// artifact under, the agent currently detected in that pane, and whether the
/// pane belongs to the calling process itself.
struct HandoffResolvedTarget: Sendable, Equatable {
  let worktreeID: String
  let worktreeName: String
  let rootPath: String
  let paneID: String
  let outgoingAgent: String?
  let outgoingLaunchObservation: AgentLaunchObservation?
  let outgoingSession: AgentSession?
  let sessionContext: HandoffStore.SessionContext?
  /// The resolved source pane is the pane the calling `prowl` process runs in.
  let isSelfHandoff: Bool
}

enum HandoffResolveError: Error {
  case resolver(TargetResolverError)
  /// No selector was given and the caller is not inside a Prowl pane.
  case noCallerPane
}

/// The pane the receiving agent was launched into.
struct HandoffLaunchedPane: Sendable, Equatable {
  let worktreeID: String
  let worktreeName: String
  let tabID: String
  let paneID: String
  let paneTitle: String
}

/// A successful CLI handoff, announced so the UI (the Hand Off HUD waiting on
/// an injected request) can correlate it with the source pane and finish.
struct HandoffCLICompletion: Sendable, Equatable {
  let action: HandoffAction
  let sourcePaneID: String
  let toAgent: String?
  let toProfileID: AgentProfile.ID?
  let toProfileName: String?
  let briefing: HandoffBriefing
  let launched: HandoffLaunchedPane?
  let failureMessage: String?
  /// True once the archive/current/context artifacts have committed, even if
  /// the receiving process could not be launched afterward.
  let artifactsReady: Bool
  /// ID generated by the HUD, or nil for an ordinary CLI handoff.
  let requestID: UUID?

  init(
    action: HandoffAction,
    sourcePaneID: String,
    toAgent: String?,
    toProfileID: AgentProfile.ID? = nil,
    toProfileName: String? = nil,
    briefing: HandoffBriefing,
    launched: HandoffLaunchedPane?,
    failureMessage: String? = nil,
    artifactsReady: Bool = true,
    requestID: UUID?
  ) {
    self.action = action
    self.sourcePaneID = sourcePaneID
    self.toAgent = toAgent
    self.toProfileID = toProfileID
    self.toProfileName = toProfileName
    self.briefing = briefing
    self.launched = launched
    self.failureMessage = failureMessage
    self.artifactsReady = artifactsReady
    self.requestID = requestID
  }
}

@MainActor
final class HandoffCommandHandler: CommandHandler {
  typealias ResolveProvider =
    @MainActor (TargetSelector, pid_t?) -> Result<HandoffResolvedTarget, HandoffResolveError>
  typealias LaunchProvider = @MainActor (HandoffResolvedTarget, AgentStartRequest) -> HandoffLaunchedPane?
  typealias ProfileProvider = @MainActor (AgentProfile.ID) -> AgentProfile?
  typealias ProfileLaunchProvider =
    @MainActor (HandoffResolvedTarget, AgentProfileLaunchPlan) -> HandoffLaunchedPane?
  /// Resumes the source session headlessly and returns its reply text
  /// (the fork briefing fallback).
  typealias ForkProvider = @Sendable (AgentResumeRequest, URL) async throws -> String
  /// Announces a completed transition (`from`, receiver display name) for the launched pane.
  typealias LaunchNotifier = @MainActor (HandoffLaunchedPane, String, String) -> Void
  /// Announces every successful save/to so the UI can observe injected requests.
  typealias CompletionObserver = @MainActor (HandoffCLICompletion) -> Void
  /// Atomically claims an exact HUD request before its transition starts.
  typealias RequestAuthorizer =
    @MainActor (UUID, HandoffRequestExpectation) -> HandoffRequestClaimResult

  /// Agents this command can launch (it injects an agent-specific kickoff command).
  static let supportedAgents = HandoffAgentSupport.launchableAgents

  private let resolveProvider: ResolveProvider
  private let launchProvider: LaunchProvider
  private let profileProvider: ProfileProvider
  private let profileLaunchProvider: ProfileLaunchProvider
  private let forkProvider: ForkProvider
  private let notifyLaunch: LaunchNotifier
  private let completionObserver: CompletionObserver
  private let requestAuthorizer: RequestAuthorizer

  private let now: @Sendable () -> Date

  init(
    resolveProvider: @escaping ResolveProvider,
    launchProvider: @escaping LaunchProvider,
    profileProvider: @escaping ProfileProvider = { _ in nil },
    profileLaunchProvider: @escaping ProfileLaunchProvider = { _, _ in nil },
    forkProvider: @escaping ForkProvider,
    notifyLaunch: @escaping LaunchNotifier = { _, _, _ in },
    completionObserver: @escaping CompletionObserver = { _ in },
    requestAuthorizer: @escaping RequestAuthorizer = { _, _ in .claimed },
    now: @escaping @Sendable () -> Date = { Date() }

  ) {
    self.resolveProvider = resolveProvider
    self.launchProvider = launchProvider
    self.profileProvider = profileProvider
    self.profileLaunchProvider = profileLaunchProvider
    self.forkProvider = forkProvider
    self.notifyLaunch = notifyLaunch
    self.completionObserver = completionObserver
    self.requestAuthorizer = requestAuthorizer

    self.now = now
  }

  func handle(envelope: CommandEnvelope) async -> CommandResponse {
    await handle(envelope: envelope, context: CLICommandContext())
  }

  func handle(envelope: CommandEnvelope, context: CLICommandContext) async -> CommandResponse {
    guard case .handoff(let input) = envelope.command else {
      return errorResponse(code: CLIErrorCode.handoffFailed, message: "Invalid command.")
    }
    if input.brief != nil, input.contextOnly {
      return errorResponse(
        code: CLIErrorCode.invalidArgument,
        message: "--brief and --no-brief are mutually exclusive."
      )
    }
    let receivingTarget: HandoffReceivingTarget?
    switch validateReceivingTarget(for: input) {
    case .accepted(let target):
      receivingTarget = target
    case .rejected(let response):
      return response
    }

    let target: HandoffResolvedTarget
    switch resolveProvider(input.selector, context.callerProcessID) {
    case .success(let resolved):
      target = resolved
    case .failure(let error):
      return mapResolveError(error)
    }

    if let response = requestAuthorizationFailure(
      input: input,
      target: target,
      receivingTarget: receivingTarget
    ) {
      return response
    }

    let briefingSource: HandoffBriefingSource
    switch briefingDecision(for: input, target: target) {
    case .source(let source):
      briefingSource = source
    case .rejected(let response):
      publishFailure(
        for: input,
        target: target,
        receivingTarget: receivingTarget,
        message: response.error?.message ?? "The handoff request was rejected."
      )
      return response
    }

    switch input.action {
    case .save:
      return await handleSave(
        input: input,
        target: target,
        briefingSource: briefingSource
      )
    case .toAgent:
      guard let receivingTarget else {
        return errorResponse(code: CLIErrorCode.invalidArgument, message: "handoff to requires a receiver.")
      }
      return await handleTo(
        input: input,
        target: target,
        receivingTarget: receivingTarget,
        briefingSource: briefingSource
      )
    }
  }

  private enum ReceivingTargetValidation {
    case accepted(HandoffReceivingTarget?)
    case rejected(CommandResponse)
  }

  private func validateReceivingTarget(for input: HandoffInput) -> ReceivingTargetValidation {
    switch (input.action, input.toAgent, input.toProfileID) {
    case (.save, nil, nil):
      return .accepted(nil)
    case (.save, _, _):
      return .rejected(
        errorResponse(
          code: CLIErrorCode.invalidArgument,
          message: "handoff save does not accept a receiving agent or Agent Profile."
        )
      )
    case (.toAgent, .some(let rawAgent), nil):
      guard
        let token = HandoffAgentSupport.normalize(rawAgent),
        let agent = DetectedAgent(rawValue: token)
      else {
        return .rejected(
          errorResponse(
            code: CLIErrorCode.invalidArgument,
            message: "handoff to requires an agent of: \(HandoffAgentSupport.supportedAgentsDescription)."
          )
        )
      }
      if input.launch, !HandoffAgentSupport.canLaunch(token) {
        return .rejected(
          errorResponse(
            code: CLIErrorCode.invalidArgument,
            message:
              "handoff can only launch: \(HandoffAgentSupport.launchableAgentsDescription). "
              + "Use --no-launch for other agents."
          )
        )
      }
      return .accepted(.runtimeDefault(agent))
    case (.toAgent, nil, .some(let profileID)):
      return .accepted(.profile(profileID))
    case (.toAgent, _, _):
      return .rejected(
        errorResponse(
          code: CLIErrorCode.invalidArgument,
          message:
            "handoff to requires exactly one receiver: an agent (launchable: "
            + "\(HandoffAgentSupport.launchableAgentsDescription)) or --agent-profile-id <uuid>."
        )
      )
    }
  }

  private func requestAuthorizationFailure(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    receivingTarget: HandoffReceivingTarget?
  ) -> CommandResponse? {
    guard let requestID = input.requestID else { return nil }
    guard input.action != .toAgent || input.launch else {
      return errorResponse(
        code: CLIErrorCode.invalidArgument,
        message: "A HUD handoff request must launch its selected receiver. Nothing was changed."
      )
    }
    guard let sourcePaneID = UUID(uuidString: target.paneID) else {
      return errorResponse(code: CLIErrorCode.invalidArgument, message: "The source pane ID is invalid.")
    }
    let operation = receivingTarget.map { HandoffRequestOperation.handoff(target: $0) } ?? .checkpoint
    let actual = HandoffRequestExpectation(sourcePaneID: sourcePaneID, operation: operation)
    switch requestAuthorizer(requestID, actual) {
    case .claimed:
      return nil
    case .mismatch:
      return errorResponse(
        code: CLIErrorCode.invalidArgument,
        message: "This HUD request does not match the source pane or destination. Nothing was changed."
      )
    case .unavailable:
      return errorResponse(
        code: CLIErrorCode.handoffRequestSuperseded,
        message: "This HUD handoff request was superseded by a fallback. Nothing was changed."
      )
    }
  }

  // MARK: - Briefing decision

  private enum BriefingDecision {
    case source(HandoffBriefingSource)
    case rejected(CommandResponse)
  }

  /// Inline when provided, context-only when explicit, error for a brief-less
  /// self-handoff (the author is on the command line — asking it to rerun with
  /// `--brief` is the cheapest correct outcome), fork for third-party sources,
  /// context-only when no safe fork exists.
  private func briefingDecision(
    for input: HandoffInput,
    target: HandoffResolvedTarget
  ) -> BriefingDecision {
    if let brief = input.brief {
      return .source(.inline(brief))
    }
    if input.contextOnly {
      return .source(.none)
    }
    if target.isSelfHandoff {
      return .rejected(
        errorResponse(
          code: CLIErrorCode.briefRequired,
          message: Self.briefRequiredMessage(input: input)
        )
      )
    }
    if let request = Self.forkRequest(
      outgoingAgent: target.outgoingAgent,
      session: target.outgoingSession,
      observation: target.outgoingLaunchObservation
    ) {
      return .source(.fork(request))
    }
    return .source(.none)
  }

  // MARK: - save

  private func handleSave(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    briefingSource: HandoffBriefingSource
  ) async -> CommandResponse {
    let store = HandoffStore(rootURL: URL(fileURLWithPath: target.rootPath, isDirectory: true))
    let coordinator = makeCoordinator(store: store)
    let timestamp = now()
    do {
      let (result, briefing) = try await coordinator.makeCheckpoint(
        outgoingAgent: target.outgoingAgent,
        sessionContext: target.sessionContext,
        note: input.note,
        briefingSource: briefingSource,
        now: timestamp
      )
      completionObserver(
        HandoffCLICompletion(
          action: .save,
          sourcePaneID: target.paneID,
          toAgent: nil,
          briefing: briefing,
          launched: nil,
          requestID: input.requestID

        )
      )
      return success(
        payload: makePayload(action: .save, save: result, briefing: briefing)
      )
    } catch HandoffBriefingError.invalidInlineBrief {
      let message = Self.invalidBriefMessage()
      publishFailure(for: input, target: target, receivingTarget: nil, message: message)
      return errorResponse(code: CLIErrorCode.invalidBrief, message: message)
    } catch {
      let message = "Failed to save handoff: \(String(describing: error))"
      publishFailure(for: input, target: target, receivingTarget: nil, message: message)
      return errorResponse(
        code: CLIErrorCode.handoffFailed,
        message: message
      )
    }
  }

  // MARK: - to

  private struct PreparedReceiver {
    let target: HandoffReceivingTarget
    let agent: DetectedAgent
    let profile: AgentProfile?
    let profilePlan: AgentProfileLaunchPlan?
  }

  private enum ReceiverPreparation {
    case accepted(PreparedReceiver)
    case rejected(CommandResponse)
  }

  private enum BriefingCollection {
    case accepted(HandoffPreparedBriefing)
    case rejected(CommandResponse)
  }

  private func collectBriefing(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    receivingTarget: HandoffReceivingTarget,
    source: HandoffBriefingSource,
    coordinator: HandoffCoordinator
  ) async -> BriefingCollection {
    do {
      return .accepted(try await coordinator.collectBriefing(source))
    } catch HandoffBriefingError.invalidInlineBrief {
      let message = Self.invalidBriefMessage()
      publishFailure(
        for: input,
        target: target,
        receivingTarget: receivingTarget,
        message: message
      )
      return .rejected(errorResponse(code: CLIErrorCode.invalidBrief, message: message))
    } catch {
      let message = "Failed to collect the handoff briefing: \(String(describing: error))"
      publishFailure(
        for: input,
        target: target,
        receivingTarget: receivingTarget,
        message: message
      )
      return .rejected(errorResponse(code: CLIErrorCode.handoffFailed, message: message))
    }
  }

  private func prepareReceiver(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    receivingTarget: HandoffReceivingTarget,
    briefing: HandoffPreparedBriefing
  ) -> ReceiverPreparation {
    guard case .profile(let profileID) = receivingTarget else {
      guard case .runtimeDefault(let agent) = receivingTarget else {
        preconditionFailure("Unknown handoff receiving target")
      }
      return .accepted(
        PreparedReceiver(target: receivingTarget, agent: agent, profile: nil, profilePlan: nil)
      )
    }
    guard let profile = profileProvider(profileID), profile.isEnabled else {
      let message = "The selected Agent Profile is missing or disabled. Nothing was changed."
      publishFailure(
        for: input,
        target: target,
        receivingTarget: receivingTarget,
        briefing: briefing.outcome,
        message: message
      )
      return .rejected(errorResponse(code: CLIErrorCode.invalidArgument, message: message))
    }
    guard input.launch else {
      return .accepted(
        PreparedReceiver(
          target: receivingTarget,
          agent: profile.runtime.agent,
          profile: profile,
          profilePlan: nil
        )
      )
    }
    do {
      let plan = try AgentProfileLaunchPlanner.plan(
        for: profile,
        homeBaseDirectory: SupacodePaths.agentProfileHomesDirectory,
        intent: .prompt(Self.kickoffPrompt(hasBriefing: briefing.outcome.wroteBriefing))
      )
      return .accepted(
        PreparedReceiver(
          target: receivingTarget,
          agent: profile.runtime.agent,
          profile: profile,
          profilePlan: plan
        )
      )
    } catch {
      let message = "The selected Agent Profile could not be prepared. Nothing was changed."
      publishFailure(
        for: input,
        target: target,
        receivingTarget: receivingTarget,
        profile: profile,
        briefing: briefing.outcome,
        message: message
      )
      return .rejected(errorResponse(code: CLIErrorCode.invalidArgument, message: message))
    }
  }

  private func launchReceiver(
    target: HandoffResolvedTarget,
    receiver: PreparedReceiver,
    outgoingAgent: String?,
    hasBriefing: Bool
  ) -> HandoffLaunchedPane? {
    switch receiver.target {
    case .runtimeDefault:
      let configuration: AgentLaunchConfiguration
      if let sourceAgent = outgoingAgent.flatMap(DetectedAgent.init(rawValue:)) {
        configuration = AgentRuntimeAdapterRegistry.inheritedConfiguration(
          from: sourceAgent,
          observation: target.outgoingLaunchObservation,
          to: receiver.agent
        )
      } else {
        configuration = .init()
      }
      return launchProvider(
        target,
        AgentStartRequest(
          agent: receiver.agent,
          intent: .prompt(Self.kickoffPrompt(hasBriefing: hasBriefing)),
          configuration: configuration
        )
      )
    case .profile:
      guard let profilePlan = receiver.profilePlan else { return nil }
      return profileLaunchProvider(target, profilePlan)
    }
  }

  private func successfulTransitionResponse(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    receiver: PreparedReceiver,
    artifacts: HandoffCoordinator.TransitionArtifacts,
    launched: HandoffLaunchedPane?
  ) -> CommandResponse {
    let toAgent = receiver.agent.rawValue
    completionObserver(
      HandoffCLICompletion(
        action: .toAgent,
        sourcePaneID: target.paneID,
        toAgent: toAgent,
        toProfileID: receiver.profile?.id,
        toProfileName: receiver.profile?.name,
        briefing: artifacts.briefing,
        launched: launched,
        requestID: input.requestID
      )
    )
    return success(
      payload: makePayload(
        action: .toAgent,
        save: artifacts.save,
        briefing: artifacts.briefing,
        toAgent: toAgent,
        toProfileID: receiver.profile?.id,
        toProfileName: receiver.profile?.name,
        archivedPath: artifacts.archivedPath,
        launched: launched
      )
    )
  }

  private func launchFailureResponse(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    receivingTarget: HandoffReceivingTarget,
    receiver: PreparedReceiver,
    artifacts: HandoffCoordinator.TransitionArtifacts
  ) -> CommandResponse {
    let message = "Progress was saved, but \(receiver.profile?.name ?? receiver.agent.rawValue) could not be launched."
    publishFailure(
      for: input,
      target: target,
      receivingTarget: receivingTarget,
      profile: receiver.profile,
      briefing: artifacts.briefing,
      artifactsReady: true,
      message: message
    )
    return errorResponse(code: CLIErrorCode.handoffFailed, message: message)
  }

  private func handleTo(
    input: HandoffInput,
    target: HandoffResolvedTarget,
    receivingTarget: HandoffReceivingTarget,
    briefingSource: HandoffBriefingSource
  ) async -> CommandResponse {
    let timestamp = now()
    let outgoing = target.outgoingAgent
    let from = outgoing ?? "agent"
    let coordinator = makeCoordinator(
      store: HandoffStore(rootURL: URL(fileURLWithPath: target.rootPath, isDirectory: true))
    )

    let preparedBriefing: HandoffPreparedBriefing
    switch await collectBriefing(
      input: input,
      target: target,
      receivingTarget: receivingTarget,
      source: briefingSource,
      coordinator: coordinator
    ) {
    case .accepted(let briefing):
      preparedBriefing = briefing
    case .rejected(let response):
      return response
    }

    let receiver: PreparedReceiver
    switch prepareReceiver(
      input: input,
      target: target,
      receivingTarget: receivingTarget,
      briefing: preparedBriefing
    ) {
    case .accepted(let prepared):
      receiver = prepared
    case .rejected(let response):
      return response
    }

    let toAgent = receiver.agent.rawValue
    let artifacts: HandoffCoordinator.TransitionArtifacts
    do {
      artifacts = try await coordinator.makeTransitionArtifacts(
        outgoingAgent: outgoing,
        toAgent: toAgent,
        sessionContext: target.sessionContext,
        briefing: preparedBriefing,
        now: timestamp
      )
    } catch {
      let message = "Failed to prepare handoff artifacts: \(String(describing: error))"
      publishFailure(
        for: input,
        target: target,
        receivingTarget: receivingTarget,
        profile: receiver.profile,
        briefing: preparedBriefing.outcome,
        message: message
      )
      return errorResponse(code: CLIErrorCode.handoffFailed, message: message)
    }

    var launched: HandoffLaunchedPane?
    if input.launch {
      launched = launchReceiver(
        target: target,
        receiver: receiver,
        outgoingAgent: outgoing,
        hasBriefing: artifacts.hasBriefing
      )
      guard let launched else {
        await coordinator.logTransition(
          from: from,
          toAgent: toAgent,
          disposition: .failed,
          briefing: artifacts.briefing,
          toProfileID: receiver.profile?.id,
          toProfileName: receiver.profile?.name,
          archivedPath: artifacts.archivedPath,
          note: input.note,
          now: timestamp
        )
        return launchFailureResponse(
          input: input,
          target: target,
          receivingTarget: receivingTarget,
          receiver: receiver,
          artifacts: artifacts
        )
      }
      notifyLaunch(launched, from, receiver.profile?.name ?? toAgent)
    }

    await coordinator.logTransition(
      from: from,
      toAgent: toAgent,
      disposition: launched.map { .pane($0.paneID) } ?? .skipped,
      briefing: artifacts.briefing,
      toProfileID: receiver.profile?.id,
      toProfileName: receiver.profile?.name,
      note: input.note,
      now: timestamp
    )

    return successfulTransitionResponse(
      input: input,
      target: target,
      receiver: receiver,
      artifacts: artifacts,
      launched: launched
    )
  }

  private func makeCoordinator(store: HandoffStore) -> HandoffCoordinator {
    HandoffCoordinator(store: store, resume: forkProvider)
  }

  // MARK: - Kickoff prompt

  nonisolated static func kickoffPrompt(hasBriefing: Bool) -> String {
    if hasBriefing {
      "Take over this Prowl workspace task. Read .prowl/handoff/current.md (the previous agent's "
        + "briefing), .prowl/handoff/context.md (generated state), and .prowl/workspace.json "
        + "(repo layout, if present), then continue from Next Steps. Do not redo work already listed "
        + "under What Has Been Done. If context.md lists a Session Context excerpt, read it before "
        + "changing code. Earlier hand-off snapshots are under .prowl/handoff/archive/ if you need "
        + "deeper history. Ask before any commit/push or destructive git."
    } else {
      "Take over this Prowl workspace task. There is no briefing from the previous agent: orient "
        + "from .prowl/handoff/context.md (generated repository and session state) and "
        + ".prowl/workspace.json (repo layout, if present). If context.md lists a Session Context "
        + "excerpt, read it before changing code. Earlier hand-off snapshots are under "
        + ".prowl/handoff/archive/ if you need history. Ask before any commit/push or destructive git."
    }
  }

  // MARK: - Fork briefing (fallback)

  nonisolated static func forkRequest(
    outgoingAgent: String?,
    session: AgentSession?,
    observation: AgentLaunchObservation?
  ) -> AgentResumeRequest? {
    guard
      let outgoingAgent,
      let agent = DetectedAgent(rawValue: outgoingAgent),
      let session,
      session.confidence == .exact || session.confidence == .high,
      AgentRuntimeAdapterRegistry.canResume(agent)
    else {
      return nil
    }
    return AgentResumeRequest(
      agent: agent,
      session: session,
      prompt: forkBriefingPrompt(),
      model: observation?.model
    )
  }

  nonisolated static func forkBriefingPrompt() -> String {
    "Prowl handoff briefing: another agent with none of your context will take over this task, "
      + "starting only from the document you write now. Reply with the complete contents of a fresh "
      + ".prowl/handoff/current.md and nothing else — a markdown document titled \"# Handoff\" with the "
      + "sections \"## Objective\", \"## Current State\", \"## What Has Been Done\", \"## Open Questions\", "
      + "\"## Risks / Watch Out\", \"## Next Steps\", and \"## Suggested Prompt For Next Agent\". "
      + "Write it entirely from what you know in this session — include only work and state you can "
      + "vouch for right now; never restate earlier notes you cannot verify. Keep Next Steps ordered "
      + "and concrete — the next agent starts there — and make Suggested Prompt For Next Agent a "
      + "ready-to-paste instruction. Do not run commands, read files, or edit anything — Prowl writes "
      + "the file from your reply. Be concise and answer in a single reply."
  }

  // MARK: - Error messages

  nonisolated static func briefRequiredMessage(input: HandoffInput) -> String {
    let command =
      switch input.action {
      case .save: "prowl handoff save --brief -"
      case .toAgent:
        if let profileID = input.toProfileID {
          "prowl handoff to --agent-profile-id \(profileID.uuidString) --brief -"
        } else {
          "prowl handoff to \(input.toAgent ?? "<agent>") --brief -"
        }
      }
    return """
      Self-handoff requires an inline briefing — you are the author. Rerun with your briefing on stdin:
        \(command) <<'EOF'
        # Handoff
        ## Objective
        …
        ## Current State
        …
        ## What Has Been Done
        …
        ## Open Questions
        …
        ## Risks / Watch Out
        …
        ## Next Steps
        …
        ## Suggested Prompt For Next Agent
        …
        EOF
      Write it from your current working knowledge. Use --no-brief only for an intentional \
      context-only handoff.
      """
  }

  nonisolated static func invalidBriefMessage() -> String {
    "The briefing is missing required sections. Include at least \"## Objective\", "
      + "\"## Current State\", and \"## Next Steps\" "
      + "(recommended: the full skeleton \(HandoffStore.briefingSections.joined(separator: " / "))). "
      + "Nothing was written — fix the briefing and rerun."
  }

  // MARK: - Payload

  private func makePayload(
    action: HandoffAction,
    save: HandoffStore.SaveResult,
    briefing: HandoffBriefing,
    toAgent: String? = nil,
    toProfileID: AgentProfile.ID? = nil,
    toProfileName: String? = nil,
    archivedPath: String? = nil,
    launched: HandoffLaunchedPane? = nil
  ) -> HandoffCommandPayload {
    HandoffCommandPayload(
      action: action,
      artifactPath: save.artifactPath,
      outgoingAgent: save.outgoingAgent,
      toAgent: toAgent,
      toProfileID: toProfileID,
      toProfileName: toProfileName,
      repos: save.repos.map {
        HandoffRepoPayload(
          name: $0.name,
          branch: $0.branch,
          isGit: $0.isGit,
          changedFileCount: $0.changedFileCount,
          insertions: $0.insertions,
          deletions: $0.deletions
        )
      },
      changedFileCount: save.totalChangedFiles,
      archivedPath: archivedPath,
      sessionContext: save.sessionContext,
      briefing: briefing.rawValue,
      hasBriefing: briefing.wroteBriefing,
      launchedPane: launched.map {
        HandoffPanePayload(
          worktreeID: $0.worktreeID,
          worktreeName: $0.worktreeName,
          tabID: $0.tabID,
          paneID: $0.paneID,
          paneTitle: $0.paneTitle
        )
      }
    )
  }

  private func publishFailure(
    for input: HandoffInput,
    target: HandoffResolvedTarget,
    receivingTarget: HandoffReceivingTarget?,
    profile: AgentProfile? = nil,
    briefing: HandoffBriefing = .none,
    artifactsReady: Bool = false,
    message: String
  ) {
    guard input.requestID != nil else { return }
    let toAgent: String? =
      switch receivingTarget {
      case .runtimeDefault(let agent): agent.rawValue
      case .profile: profile?.runtime.agent.rawValue
      case nil: nil
      }
    let toProfileID: AgentProfile.ID? =
      switch receivingTarget {
      case .profile(let profileID): profileID
      case .runtimeDefault, nil: nil
      }
    completionObserver(
      HandoffCLICompletion(
        action: input.action,
        sourcePaneID: target.paneID,
        toAgent: toAgent,
        toProfileID: toProfileID,
        toProfileName: profile?.name,
        briefing: briefing,
        launched: nil,
        failureMessage: message,
        artifactsReady: artifactsReady,
        requestID: input.requestID
      )
    )
  }

  // MARK: - Response helpers

  private func success(payload: HandoffCommandPayload) -> CommandResponse {
    do {
      return try CommandResponse(
        ok: true,
        command: "handoff",
        schemaVersion: "prowl.cli.handoff.v2",
        data: RawJSON(encoding: payload)
      )
    } catch {
      return errorResponse(code: CLIErrorCode.handoffFailed, message: "Failed to encode response.")
    }
  }

  private func mapResolveError(_ error: HandoffResolveError) -> CommandResponse {
    switch error {
    case .resolver(.notFound(let message)):
      return errorResponse(code: CLIErrorCode.targetNotFound, message: message)
    case .resolver(.notUnique(let message)):
      return errorResponse(code: CLIErrorCode.targetNotUnique, message: message)
    case .noCallerPane:
      return errorResponse(
        code: CLIErrorCode.sourceRequired,
        message: "No source pane: run this inside a Prowl pane (the calling agent's pane becomes "
          + "the source), or pass an explicit selector (--pane p3, --tab t2, --worktree <name>)."
      )
    }
  }

  private func errorResponse(code: String, message: String) -> CommandResponse {
    CommandResponse(
      ok: false,
      command: "handoff",
      schemaVersion: "prowl.cli.handoff.v2",
      error: CommandError(code: code, message: message)
    )
  }
}
